const books =[
    {title:"The cock crows", author:"Theresa", publication:"08/04/31", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"},
    {title:"Things fall apart", author:"chinedu", publication:"04/02/21", type:"fiction"}
]

module.exports=books